import React from 'react';
import SEO from '../components/SEO';

const TermsOfService = () => {
    return (
        <div className="p-8 max-w-7xl mx-auto text-slate-300">
            <SEO title="Terms of Use" description="Terms of use and disclaimers for DB Playground tools." />
            <h1 className="text-3xl font-bold mb-6 text-white">Terms of Use</h1>
            <div className="prose prose-invert max-w-none">
                <p className="mb-4">Last updated: {new Date().toLocaleDateString()}</p>
                <p className="mb-4">
                    Welcome to DB Playground. By using our script generation and database tools, you agree to these Terms of Use.
                </p>

                <div className="bg-red-900/20 border border-red-500/50 rounded-lg p-4 my-6">
                    <h3 className="text-red-400 font-bold text-lg mb-2">IMPORTANT DISCLAIMER</h3>
                    <p className="text-red-200">
                        The scripts and tools provided on this website are for educational and productivity purposes.
                        <strong> Always verify generated scripts in a non-production environment before executing them.</strong>
                    </p>
                </div>

                <h2 className="text-xl font-bold text-white mt-8 mb-4">1. Use of Tools</h2>
                <p className="mb-4">
                    DB Playground provides client-side tools for generating SQL scripts (Backup, Rollback, Alter Table, etc.).
                    You acknowledge that:
                </p>
                <ul className="list-disc pl-6 mb-4 space-y-2">
                    <li>You are solely responsible for reviewing any code generated by this tool.</li>
                    <li>You should test all scripts in a development environment first.</li>
                    <li>The Company is not responsible for any data loss, corruption, or downtime resulting from the use of these tools.</li>
                </ul>

                <h2 className="text-xl font-bold text-white mt-8 mb-4">2. No Warranty</h2>
                <p className="mb-4">
                    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
                </p>

                <h2 className="text-xl font-bold text-white mt-8 mb-4">3. Intellectual Property</h2>
                <p className="mb-4">
                    This tool is provided as a portfolio project. You are free to use the generated scripts for personal or commercial projects.
                </p>

                <h2 className="text-xl font-bold text-white mt-8 mb-4">4. Changes to Terms</h2>
                <p className="mb-4">
                    We reserve the right to modify these terms at any time. Continued use of the tools constitutes acceptance of updated terms.
                </p>
            </div>
        </div>
    );
};

export default TermsOfService;
