import React from 'react';
import { motion } from 'framer-motion';

const Guide = () => {
    return (
        <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-8"
        >
            {/* Definition Bento Card */}
            <div className="bg-slate-900/40 border border-slate-800/60 backdrop-blur-xl rounded-[2.5rem] p-8 relative overflow-hidden group">
                <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-indigo-600/5 rounded-full blur-[100px] pointer-events-none" />
                <div className="relative z-10">
                    <h2 className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-500 mb-4">Functional Definition</h2>
                    <p className="text-xl md:text-2xl font-black text-white tracking-tighter leading-tight max-w-2xl">
                        An execution plan is the <span className="text-indigo-400">logical roadmap</span> generated by SQL Server to visualize the precise computational path of your query.
                    </p>
                </div>
            </div>

            {/* Basics Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-slate-900/40 border border-slate-800/60 rounded-[2rem] p-6 space-y-4">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-orange-400">
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7-7 7" />
                            </svg>
                        </div>
                        <h3 className="text-sm font-black text-white uppercase tracking-widest italic">The Golden Rule</h3>
                    </div>
                    <h4 className="text-lg font-black text-slate-200 tracking-tight">Read from Right to Left</h4>
                    <p className="text-xs text-slate-500 font-medium leading-relaxed">
                        Data flows backwards in the plan. The furthest right operators are your raw sources (Tables, Indexes), and results move towards the left for sorting and final output.
                    </p>
                </div>

                <div className="bg-slate-900/40 border border-slate-800/60 rounded-[2rem] p-6 space-y-4">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                            </svg>
                        </div>
                        <h3 className="text-sm font-black text-white uppercase tracking-widest italic">Signal Detection</h3>
                    </div>
                    <h4 className="text-lg font-black text-slate-200 tracking-tight">Indicators & Warnings</h4>
                    <div className="space-y-2">
                        {[
                            { label: 'Arrow Thickness', desc: 'Represents relative row count.' },
                            { label: 'Cost %', desc: 'Identifies primary bottlenecks.' },
                            { label: 'Yellow Marks', desc: 'Critical performance warnings.' }
                        ].map((item, i) => (
                            <div key={i} className="flex items-center justify-between text-[10px]">
                                <span className="font-black text-slate-600 uppercase tracking-widest">{item.label}</span>
                                <span className="font-medium text-slate-400">{item.desc}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Operator Cluster */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
                <div className="space-y-4">
                    <header className="flex items-center gap-2 px-2">
                        <div className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]" />
                        <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Optimized Patterns</h3>
                    </header>
                    <div className="space-y-3">
                        {[
                            { name: 'Index Seek', type: 'Precision', desc: 'Direct B-Tree traversal. The fastest data access method.' },
                            { name: 'Nested Loops', type: 'Join Strategy', desc: 'Efficiently matches small datasets to indexed sources.' }
                        ].map((op, i) => (
                            <div key={i} className="bg-slate-950/40 border border-slate-800/50 rounded-2xl p-4 group hover:border-emerald-500/30 transition-all">
                                <div className="flex justify-between items-start mb-1">
                                    <span className="text-xs font-black text-white uppercase tracking-tighter">{op.name}</span>
                                    <span className="text-[8px] font-black text-emerald-400 uppercase tracking-widest bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/20">{op.type}</span>
                                </div>
                                <p className="text-[10px] text-slate-500 font-medium leading-relaxed">{op.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="space-y-4">
                    <header className="flex items-center gap-2 px-2">
                        <div className="w-2 h-2 rounded-full bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]" />
                        <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Bottleneck Alerts</h3>
                    </header>
                    <div className="space-y-3">
                        {[
                            { name: 'Table Scan', type: 'High Cost', desc: 'Linear reading of all rows. High I/O overhead on large tables.' },
                            { name: 'Key Lookup', type: 'Double Work', desc: 'Index usage followed by clustered lookups for missing columns.' },
                            { name: 'TempDB Spool', type: 'Memory Spill', desc: 'Memory shortage forcing computational spills to disk.' }
                        ].map((op, i) => (
                            <div key={i} className="bg-slate-950/40 border border-slate-800/50 rounded-2xl p-4 group hover:border-red-500/30 transition-all">
                                <div className="flex justify-between items-start mb-1">
                                    <span className="text-xs font-black text-white uppercase tracking-tighter">{op.name}</span>
                                    <span className="text-[8px] font-black text-red-400 uppercase tracking-widest bg-red-500/10 px-2 py-0.5 rounded-full border border-red-500/20">{op.type}</span>
                                </div>
                                <p className="text-[10px] text-slate-500 font-medium leading-relaxed">{op.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Strategy Protocol */}
            <div className="bg-gradient-to-br from-indigo-900/20 to-slate-900/40 border border-indigo-500/20 rounded-[2.5rem] p-8 relative overflow-hidden">
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
                    <div className="space-y-2">
                        <h3 className="text-xs font-black text-indigo-400 uppercase tracking-widest italic">Optimization Protocol</h3>
                        <h4 className="text-2xl font-black text-white tracking-tighter">Query Tuning Strategy</h4>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3">
                        {[
                            'Identify operators with > 50% relative cost.',
                            'Verify row count estimates vs actual output.',
                            'Eliminate Scans via optimized indexing.',
                            'Replace Lookups with Covering Indexes.'
                        ].map((step, i) => (
                            <div key={i} className="flex items-center gap-3">
                                <div className="w-5 h-5 rounded-full bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center text-indigo-400 text-[10px] font-black">{i+1}</div>
                                <span className="text-[11px] font-bold text-slate-300 tracking-tight uppercase">{step}</span>
                            </div>
                        ))}
                    </div>
                    </div>
            </div>
        </motion.div>
    );
};

export default Guide;
